spring.application.name=AppointmentSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_system
spring.datasource.username=postgres
spring.datasource.password=2004
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

